== Problems to solve

=== Is Current Working Directory reliable for unit-tests? --- Not always

Sometimes, I want my JUnit-based tests in Java to write a file. Where to locate the file? The simplest idea would be to write the file immediately under the project directory. Let me show you an example.

- I have a Gradle Multi-project https://github.com/kazurayam/unittest-helper
- In this parent project, I have a Gradle sub-project link:https://github.com/kazurayam/unittest-helper/tree/develop/app[`:app`].
- In this sub-project, I have a JUnit5-based test class link:https://github.com/kazurayam/unittest-helper/blob/develop/app/src/test/java/com/kazurayam/unittesthelperdemo/OutputIntoCurrentWorkingDirectoryTest.java[`com.kazurayam.unittesthelperdemo.OutputIntoCurrentWorkingDirectoryTest`]
- If you have a look at the source, you would find that this test calls `java.nio.file.Paths.get(String fileName)`, will locate a file `sample1.txt` in the *current working directory* runtime, as follows:
[source,java]
----
include::../app/src/test/java/com/kazurayam/unittesthelperdemo/OutputIntoCurrentWorkingDirectoryTest.java[lines=26..31]
----
- When I run this test, I will get the file in the sub-project's directory, as follows
[source]
----
$ pwd
~/github/unittest-helper
:~/github/unittest-helper (develop *)
$ tree -L 1 app
app
├── build
├── build.gradle
├── sample1.txt
└── src

3 directories, 2 files
----
The `sample1.txt` file was written into the *current working directory*, which is the sub-project's directory. OK. This is what I expected.

Now, I would show you another sample code. It will show you a call to `Paths.get(String fileName)` does not necessarily write a file into the project directory. Have a look at a sub-project link:https://github.com/kazurayam/unittest-helper/tree/develop/selenium-webdriver-junit5[`selenium-webdriver-junit5`].

____
The `selenium-webdriver-junit` project is quoted from the sample code of the book link:https://github.com/bonigarcia/selenium-webdriver-java[
Boni García, "Hands-On Selenium WebDriver with Java"]
____

It contains:

- link:https://github.com/kazurayam/unittest-helper/blob/develop/selenium-webdriver-junit5/build.gradle[selenium-webdriver-junit5/build.gradle]
- link:https://github.com/kazurayam/unittest-helper/blob/develop/selenium-webdriver-junit5/src/test/java/io/github/bonigarcia/webdriver/jupiter/screenshots/ScreenshotPngJupiterTest.java[ScreenshotPngJupiterTest.java]

The test class has a line:
[source,java]
----
        Path destination = Paths.get("screenshot.png");
----
So I expect that the `ScreeshotPngJupiterTest.java` will write a file immediately under the sub-project directory. However, in fact when I ran the test, I was surprised to find the file `screenshot.png` was written into the parent project directory, not into the sub-project directory.

[source,commandline]
----
$ pwd
~/github/unittest-helper

$ gradle :selenium-webdriver-junit5:test
...(a few minutes passed)

$ tree -L 2 .
.
...
├── build.gradle
...
├── screenshot.png           <===
├── selenium-webdriver-junit5
│   ├── README.md
│   ├── build
│   ├── build.gradle
│   └── src
└── settings.gradle

16 directories, 29 files
----

Why the `screenshot.png` file was written into the parent project `unittest-helper` directory? Why not the file was written into the sub-project `selenium-webdriver-junit5` directory? This is the original problem I got.

I studied the codes and found the cause of the issue. In the `selenium-webdriver-junit5/build.gradle` I found a line:

[source]
----
test {
    ...
    systemProperty System.properties
}
----

With this single line, the problem occurred. When I ran a command `gradle :selenium-webdriver-junit5:test` in the command line, the `System.properites` contained the `System.getProperty("user.dir")` with the value equals to the parent project's directory, which was passed to the test classes invoked. Consequently in the test class, a call to `java.nio.file.Paths.get(String fileName)` found the `System.getProperty("user.dir")` has the path of the parent project directory, not the sub-project directory.

Consequently I learned that I should not use `java.nio.file.Paths.get(String fileName)` in the test classes at all because it does not necessarily return the path of project directory.

But how to locate the output files from tests without `Paths.get(String)`? The following post in the Gradle forum gave me a clue:

- link:https://discuss.gradle.org/t/how-do-i-set-the-working-directory-for-testng-in-a-multi-project-gradle-build/7379/7[Gradle Forums, How do I set the working dreictory for TestNG in a multi-project Gradle build?]

____
luke_daley
Gradle Employee
Nov '13

Loading from the filesystem using relative paths during unit tests is problematic because different environments will set a different working directory for the test process. For example, Gradle uses the projects directory while IntelliJ uses the directory of the root project.

The only really safe way to solve this problem is to load via the classpath. Is this a possibility for your scenario?
____

OK, I would try that.







=== Organizing output files from tests; it requires efforts

The easiest way to locate an output file from a unit-test is to call `java.io.File("some-file.txt")` or `java.nio.Paths("some-file.txt")`. Then the `some-file.txt` will be located under the current working directory = `System.getProperty("user.dir")`. Using Maven and Gradle, the current working directory will usually be equal to the project's directory. However, you should be careful. If you are dependent on calling `java.io.File(relative path)` too often, you will get a lot of temporary files located in the project directory, like this.

[source]
----
.
├── 2023.10.24_22.07.27.742-7440524241d0dbd63ca5eec377b6455c.png    --- x
├── 2023.10.24_22.07.29.333-7440524241d0dbd63ca5eec377b6455c.png    --- x
├── build
│   ├── allure-results
│   ├── classes
│   ├── downloads
│   ├── generated
│   ├── reports
│   ├── resources
│   ├── test-results
│   └── tmp
├── build.gradle
├── extentReport.html    --- x
├── fullpage-screenshot-chrome.png    --- x
├── gradle
│   └── wrapper
├── gradlew
├── gradlew.bat
├── login.har    --- x
├── my-pdf.pdf    --- x
├── pom.xml
├── screenshot.png    --- x
├── src
│   ├── main
│   └── test
├── target
│   ├── classes
│   ├── generated-sources
│   ├── generated-test-sources
│   ├── maven-status
│   └── test-classes
├── testAccessibility.json    --- x
├── webdrivermanager.pdf    --- x
├── webdrivermanager.png    --- x
└── webelement-screenshot.png    --- x

20 directories, 15 files
----

Here the files labeled with "--- x" are the temporary output files created by the unit-tests.

Temporary files located in the project directory make the project tree dirty. The files scattered in the project directory are difficult to manage. If you want to remove them, you have to choose each files and delete them one by one manually.

Rather, I want to create a dedicated directory where all test classes should write their output into. I would list it in the `.gitignore` file to exclude the temporary files out of the git repository.

