=== Example8 Removing the output directory recursively

The `TestOutputOrganizer` class implements `cleanOutputDirectory()` method which removes the output directory recursively. See the following sample test class.

[source, java]
----
include::../app/src/test/java/io/github/someone/somestuff/SampleTest.java[lines=1..45]
----
link:https://github.com/kazurayam/unittest-helper/blob/develop/app/src/test/java/io/github/someone/somestuff/SampleTest.java[source]

This will print the following in the console:

[source]
----
[test_write_file] output is found at ~/github/unittest-helper/app/build/tmp/testOutput/io.github.someone.somestuff.SampleTest/test_write_file/sample_20231104_081132.txt
[test_write_file_once_more] output is found at ~/github/unittest-helper/app/build/tmp/testOutput/io.github.someone.somestuff.SampleTest/test_write_file_once_more/sample_20231104_081132.txt
----

The `@BeforeClass`-annotated method is invoked once as soon as this test class started only once. By calling `too.cleanOutputDirectory()`, the `test-output` directory will be removed.

This method is useful when the test class writes files with timestamp in its name. If you do NOT clean the dir, you will accumulate a lot of files with different timestamps in the file name. For example:

[source]
----
app/build/tmp/testOutput
└── io.github.someone.somestuff.SampleTest
    └── test_write_file
        ├── sample_20231103_090143.txt
        ├── sample_20231103_094723.txt
        ├── sample_20231103_094759.txt
        ├── sample_20231103_094810.txt
        └── sample_20231103_094817.txt
----

By `cleanOutputDirectory`, you would have a cleaner result, like:

[source]
----
app/build/tmp/testOutput
└── io.github.someone.somestuff.SampleTest
    └── test_write_file
        └── sample_20231103_094817.txt
----

There is `cleanOutputSubDirectory()` method as well. This will choose a specific sub directory specified by `setSubDir(Path subDir)` method of the `TestOutputOrganizer.Builder` class. The `cleanOutputSubDirectory()` will leave other subdirectories in the output directory untouched.

