=== Example11 More layers of directory under the output sub-directory

The link:https://github.com/kazurayam/unittest-helper/blob/develop/app/src/test/java/io/github/someone/somestuff/SampleTest.java[io.github.someone.somestuff.SampleTest] class has one more test method:

[source]
----
include::../app/src/test/java/io/github/someone/somestuff/SampleTest.java[lines=50..60]
----

When you ran this test, you would get the output directory as follows:

```
$ tree app/build/tmp/testOutput
app/build/tmp/testOutput
└── io.github.someone.somestuff.SampleTest
    ├── test_write_file
    │   └── sample_20231103_124015.txt
    └── test_write_file_once_more
        └── sample_20231103_124015.txt
```

Please find that one more directory layer is inserted between the output dir and the files.

- `test_write_file`
- `test_write_file_once_more`

How these directories were created? If you read the source of the test class, you would find that it effectively executed the following calls

[source]
----
    Path p = too.resolveOutut("test_write_file/sample_20231103_124015.txt");
----

and

[source]
----
    Path p = too.resolveOutut("test_write_file_once_more/sample_20231103_124015.txt");
----

Note that the parameter string to the `resolveOutput(String)` method can contain `/`, which represents one or more directories under the output sub-directory. For example, you can insert a directory of which name stands for the test method name. This technique makes it easy to organize output files created by multiple methods in a single test class.

