= Unit Test Helper

- author: kazurayam
- date: Nov, 2034
- source project: link:https://github.com/kazurayam/unittest-helper[]
- javadoc: link:https://kazurayam.github.io/unittest-helper/api[]]

== Problems to solve

=== Is "Current Working Directory" reliable for unit-tests? --- Not always

I encountered some difficulties in a TestNG test case in a Gradle Multiproject. I expected that a call to `System.getProperty("user.dir")` would return the Path of sub-project's directory. In most cases, it works fine but sometimes it mal-functioned. See the following post for detail:

- https://github.com/kazurayam/selenium-webdriver-java/issues/22

I haven't managed to find out the reason why the current working directory got different from the project directory. I have given up trying to find.

The following post in the Gradle forum gave me a clue:

- link:https://discuss.gradle.org/t/how-do-i-set-the-working-directory-for-testng-in-a-multi-project-gradle-build/7379[]

____
luke_daley
Gradle Employee
Nov '13

Loading from the filesystem using relative paths during unit tests is problematic because different environments will set a different working directory for the test process. For example, Gradle uses the projects directory while IntelliJ uses the directory of the root project.

The only really safe way to solve this problem is to load via the classpath. Is this a possibility for your scenario?
____

=== I want my test classes to write files into a single dedicated directory, not under the current working directory

In the book link:https://github.com/bonigarcia/selenium-webdriver-java["Selenium WebDriver in Java" by Boni Garcia], which is very good book, the sample test classes write a lot of files into the sub-project's root directory. In my opinion, it is a bad practice. I want to create a dedicated directory where all test classes write their output into. See the following issue for more detail.

- https://github.com/kazurayam/selenium-webdriver-java/issues/8

== Solution

This project provides a Java class `com.kazurayam.unittest.TestHelper`.

The `TestHelper` helps your unit tests to save files into a dedicated directory in the Maven/Gradle project. Using this class, you can easily prepare a directory into which your unit tests can write files. The location of the output directory is resolved via the classpath of the unit-test class. The `TestHelper` does ot depend on the value returned by `System.getProperty("user.dir")`.

The `TestHelper` class works with any unit-testing frameworks: JUnit4, JUnit5 and TestNG.

The `TestHelper` class is compiled by Java8.

== Description by examples

=== Example 1: Resolving a file path by Current Working Directory

[source,java]
----
include::../app/src/test/java/com/kazurayam/unittesthelperdemo/HelperlessTest.java[]
----

This code calls `Paths.get("sample1_txt")` to resolve the path of output file. Many developers would do the same in their own codes. This code prints the following message:

----
> Task :app:testClasses
[test_write_under_current_working_directory] p = ~/github/unittest-helper/app/sample1.txt
----

The call to `Paths.get(p)` interpretes a relative path to the runtime *Current Working Directory* of the process. In the above case, `~/github/unittest-helper/app/` is the current working directory, and it happened to be equal to the project directory.

Is the current working directory equal to the project directory? --- Usually yes. But sometimes not. When the current working directory has got to be different from the project directory, it will confuse us very much. So I do not like to depend on the current working directory in my unit-tests.

=== Example 2 : resolve the project dir via classpath

[source, java]
----
include::../app/src/test/java/com/kazurayam/unittesthelperdemo/WithHelperTest.java[lines=1..18]
----

`new TestHelper(this.getClass()).getProjectDir()` returns the `java.nio.file.Path` of the project directory.

This test prints the following result in the console:

----
sublistPattern [build, classes, java, test] is found in the code source path [Users, kazurayam, github, unittest-helper, app, build, classes, java, test] at the index 5
[test_getProjectDir] projectDir = ~/github/unittest-helper/app
----

This message tells how `TestHelper.getProject()` internally works.

1. The constructor call `new TestHelper(this.getClass())` tells the `TestHelper` instance that the class was loaded from the directory `/Users/kazurayam/github/unittest-helper/app/build/classes/java/test`.
2. The `TestHelper` internally tries to find out which build tool you used: Maven or Gradle? If you used Maven, the project directory would have a subdirectory `target/test-classes`. So `TestHelper` tries to find `target/test-classes` in the code source path. If the pattern is found, then the parent directory of the `target` directory is presumed to be the project directory. If you used Gradle, the project directory would have a subdirectory `build/classes/java/test`. So `TestHelper` tries to find `build/classes/java/test` in the code source path. When the subdirectory pattern is found in the code source path, then the parent directory of the `build` directory is presumed to be the project dir.

The following patterns are implemented in the `com.kazurayam.unittest.ProjectRepositoryResolver` class:

- [target, test-classes]
- [build, classes, java, test]
- [build, classes, groovy, test]
- [build, classes, kotlin, test]

You can add more sublist patterns for your own need by calling the `TestHelper.addSublistPattern(List<String>)` method.

=== Example 3 : locate the default output directory `test-output`

Quickly find the `test-output` directory by calling `getOutputDir()`.

[source, java]
----
include::../app/src/test/java/com/kazurayam/unittesthelperdemo/WithHelperTest.java[lines=19..24]
----

=== Example 3 : create a custom output directory

[source, java]
----
include::../app/src/test/java/com/kazurayam/unittesthelperdemo/WithHelperTest.java[lines=26..33]
----

=== Example 4 : write a file into the default output directory

[source, java]
----
include::../app/src/test/java/com/kazurayam/unittesthelperdemo/WithHelperTest.java[lines=38..45]
----

=== Example 5 : write a file into a subdirectory under the test-output

[source, java]
----
include::../app/src/test/java/com/kazurayam/unittesthelperdemo/WithHelperTest.java[lines=47..53]
----

=== Example 6 : write a file into a custom output directory

[source, java]
----
include::../app/src/test/java/com/kazurayam/unittesthelperdemo/WithHelperTest.java[lines=58..65]
----
